# Generated by Django 2.0.9 on 2018-11-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('abbvr', models.CharField(blank=True, max_length=10, null=True)),
                ('clg_code_no', models.CharField(blank=True, max_length=11, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'college_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CollegeInfos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('college', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'college_infos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CollegeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('elsi_clg_id', models.IntegerField(blank=True, null=True)),
                ('clg_code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('is_elsi', models.IntegerField(db_column='IS_eLSI')),
                ('is_efsi', models.IntegerField(db_column='IS_eFSI')),
                ('eyic_allowed', models.IntegerField(db_column='eYIC_allowed')),
                ('college_name', models.CharField(blank=True, max_length=500, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('district', models.CharField(blank=True, max_length=19, null=True)),
                ('city', models.CharField(blank=True, max_length=26, null=True)),
                ('pincode', models.CharField(blank=True, max_length=9, null=True)),
                ('address', models.CharField(blank=True, max_length=114, null=True)),
                ('college_type', models.IntegerField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=132, null=True)),
                ('coordinates', models.CharField(blank=True, max_length=24, null=True)),
                ('flagged', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'college_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeetWorkshopAttendeeDtls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=6)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=25)),
                ('alt_number', models.CharField(max_length=25)),
                ('attendee_type', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meet_workshop_attendee_dtls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeetWorkshopForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_id', models.IntegerField()),
                ('state', models.CharField(max_length=40)),
                ('district', models.CharField(blank=True, max_length=200, null=True)),
                ('clg_code', models.CharField(blank=True, max_length=50, null=True)),
                ('college_name', models.CharField(max_length=100)),
                ('no_of_attendee', models.IntegerField()),
                ('loi_status', models.CharField(blank=True, max_length=100, null=True)),
                ('is_elsi', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meet_workshop_form',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbvr', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'states',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VenueDtls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clg_id', models.CharField(blank=True, max_length=20, null=True)),
                ('college_name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('detail', models.CharField(max_length=40)),
                ('active', models.IntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('time_day1', models.CharField(max_length=255)),
                ('time_day2', models.CharField(max_length=255)),
                ('coordinator', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=500)),
                ('email_id', models.CharField(max_length=500)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'venue_dtls',
                'managed': False,
            },
        ),
    ]
